### PR TITLE
Added hosp to messages and added to location check

### PR DESCRIPTION
**Pull request by gcgibson**

### CODE REVIEW

**Comment by gcgibson** [comment]
Please wait till @NutchaW reviews to merge.

**Review by NutchaW — CHANGES_REQUESTED** [review]
1. `verify_targets()` don't seem to have the valid targets for hospitalizations? Same with `verify_types()`. 
2. You should make a change to `verify_point()` since there are some hard coded target in there (we check the validity of point based on what the target is). There are some hospitalization targets that are not in the ili challenge.
3. Maybe add more unit tests for hospitalizations?

**Comment by gcgibson** [comment]
Awesome, thanks for looking! Yeah I'm not quite done yet, but I was going to commit in verify_xxxx chunks so that I don't loose my mind haha

**Comment by gcgibson** [comment]
Awesome, just changed `verify_point` to use the challenge argument instead.

**Review by NutchaW — CHANGES_REQUESTED** [review]
1. `verify_entry()` calls `verify_point()` so we need to add the challenge argument in `verify_point()` called in `verify_entry()`  function. 
2. increment the package version in the description

A quick check would be to unit test  `verify_entry()` for all the challenges since it calls other verify functions, and that hopefully they all should pass. 

Thanks for adding on to these!

**Comment by gcgibson** [comment]
Adding some more unit tests then will request another review from @NutchaW

**Pull request merged**
